## Introduction to Python

 * [numpy Math functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html)
 * [numpy Statistical functions](https://numpy.org/doc/stable/reference/routines.statistics.html)

In [33]:
import numpy as np

### Create an array called: `abs_mag`
* 100 evenly spaced point between -5.0 and 10.0

In [34]:
abs_mag = np.linspace(-5, 10, 100)

abs_mag

array([-5.        , -4.84848485, -4.6969697 , -4.54545455, -4.39393939,
       -4.24242424, -4.09090909, -3.93939394, -3.78787879, -3.63636364,
       -3.48484848, -3.33333333, -3.18181818, -3.03030303, -2.87878788,
       -2.72727273, -2.57575758, -2.42424242, -2.27272727, -2.12121212,
       -1.96969697, -1.81818182, -1.66666667, -1.51515152, -1.36363636,
       -1.21212121, -1.06060606, -0.90909091, -0.75757576, -0.60606061,
       -0.45454545, -0.3030303 , -0.15151515,  0.        ,  0.15151515,
        0.3030303 ,  0.45454545,  0.60606061,  0.75757576,  0.90909091,
        1.06060606,  1.21212121,  1.36363636,  1.51515152,  1.66666667,
        1.81818182,  1.96969697,  2.12121212,  2.27272727,  2.42424242,
        2.57575758,  2.72727273,  2.87878788,  3.03030303,  3.18181818,
        3.33333333,  3.48484848,  3.63636364,  3.78787879,  3.93939394,
        4.09090909,  4.24242424,  4.39393939,  4.54545455,  4.6969697 ,
        4.84848485,  5.        ,  5.15151515,  5.3030303 ,  5.45

### Write an expression to compute:

$$ \large 
5\log _{10}\left({\frac {50}{10}}\right) + \mathrm{abs\_mag}
$$

- Pay attention to the type of logarithm!
- Call the output array: `app_mag_50`

In [35]:
app_mag_50 = 5*np.log10(50/10) + abs_mag
app_mag_50

array([-1.50514998e+00, -1.35363483e+00, -1.20211968e+00, -1.05060452e+00,
       -8.99089372e-01, -7.47574221e-01, -5.96059069e-01, -4.44543918e-01,
       -2.93028766e-01, -1.41513615e-01,  1.00015368e-02,  1.61516688e-01,
        3.13031840e-01,  4.64546991e-01,  6.16062143e-01,  7.67577294e-01,
        9.19092446e-01,  1.07060760e+00,  1.22212275e+00,  1.37363790e+00,
        1.52515305e+00,  1.67666820e+00,  1.82818336e+00,  1.97969851e+00,
        2.13121366e+00,  2.28272881e+00,  2.43424396e+00,  2.58575911e+00,
        2.73727426e+00,  2.88878942e+00,  3.04030457e+00,  3.19181972e+00,
        3.34333487e+00,  3.49485002e+00,  3.64636517e+00,  3.79788032e+00,
        3.94939548e+00,  4.10091063e+00,  4.25242578e+00,  4.40394093e+00,
        4.55545608e+00,  4.70697123e+00,  4.85848639e+00,  5.01000154e+00,
        5.16151669e+00,  5.31303184e+00,  5.46454699e+00,  5.61606214e+00,
        5.76757729e+00,  5.91909245e+00,  6.07060760e+00,  6.22212275e+00,
        6.37363790e+00,  

### What is the *AVERAGE* of the values in `app_mag_50`

In [36]:
np.mean(app_mag_50)

5.994850021680095

### How many values of `app_mag_50` are less than 6.0?

In [37]:
len(app_mag_50[app_mag_50<6])

50

### How many values of `app_mag_50` are between 2.0 and 4.0?

In [38]:
len(app_mag_50[(app_mag_50 > 2) & (app_mag_50 < 4)])

13

### Write an expression to compute:

$$ \large 
5\log _{10}\left({\frac {500}{10}}\right) + \mathrm{abs\_mag}
$$

* Call the output array: `app_mag_500`

In [39]:
app_mag_500 = 5*np.log10(500/10) + abs_mag
app_mag_500

array([ 3.49485002,  3.64636517,  3.79788032,  3.94939548,  4.10091063,
        4.25242578,  4.40394093,  4.55545608,  4.70697123,  4.85848639,
        5.01000154,  5.16151669,  5.31303184,  5.46454699,  5.61606214,
        5.76757729,  5.91909245,  6.0706076 ,  6.22212275,  6.3736379 ,
        6.52515305,  6.6766682 ,  6.82818336,  6.97969851,  7.13121366,
        7.28272881,  7.43424396,  7.58575911,  7.73727426,  7.88878942,
        8.04030457,  8.19181972,  8.34333487,  8.49485002,  8.64636517,
        8.79788032,  8.94939548,  9.10091063,  9.25242578,  9.40394093,
        9.55545608,  9.70697123,  9.85848639, 10.01000154, 10.16151669,
       10.31303184, 10.46454699, 10.61606214, 10.76757729, 10.91909245,
       11.0706076 , 11.22212275, 11.3736379 , 11.52515305, 11.6766682 ,
       11.82818336, 11.97969851, 12.13121366, 12.28272881, 12.43424396,
       12.58575911, 12.73727426, 12.88878942, 13.04030457, 13.19181972,
       13.34333487, 13.49485002, 13.64636517, 13.79788032, 13.94

### What is the *MEDIAN* of the values in `app_mag_500`

In [40]:
np.median(app_mag_500)

10.994850021680094

### How many values of `app_mag_500` are less than 6.0?

In [41]:
len(app_mag_500[app_mag_500 < 6])

17

### How many values of `app_mag_500` are between 11.0 and 14.0?

In [42]:
len(app_mag_500[(app_mag_500 > 11) & (app_mag_500 < 14)])

20

### Write an expression to compute:

$$ \large 
3.26 \times 10^{\mathrm{\,X}}
$$

#### Where

$$ \large 
X =  \frac{11\, -\, \mathrm{abs\_mag}}{5}
$$


* Call the output array: `dim_distance`

In [43]:
dim_distance = 3.26 * (10*np.exp((11-abs_mag)/5))
dim_distance

array([799.76048443, 775.88883656, 752.72972149, 730.26187118,
       708.46465242, 687.31804786, 666.80263765, 646.89958159,
       627.59060182, 608.85796606, 590.68447131, 573.05342805,
       555.94864492, 539.35441385, 523.25549562, 507.63710589,
       492.48490162, 477.78496785, 463.523805  , 449.68831642,
       436.26579637, 423.24391836, 410.61072383, 398.35461116,
       386.46432502, 374.92894604, 363.73788078, 352.88085199,
       342.34788919, 332.12931948, 322.21575872, 312.59810283,
       303.26751952, 294.21544008, 285.43355161, 276.9137893 ,
       268.64832908, 260.62958042, 252.85017935, 245.30298171,
       237.98105657, 230.87767988, 223.98632831, 217.30067321,
       210.81457487, 204.52207681, 198.41740036, 192.49493932,
       186.74925483, 181.17507039, 175.76726697, 170.52087835,
       165.43108655, 160.49321737, 155.70273617, 151.05524362,
       146.54647174, 142.17227992, 137.92865115, 133.81168832,
       129.81761063, 125.94275016, 122.18354845, 118.53

### What fraction of the values of `dim_distance` are greater than 10?

In [44]:
len(dim_distance[dim_distance > 10]) / len(dim_distance)

1.0

### What fraction of the values of `dim_distance` are greater than 100?

In [45]:
len(dim_distance[dim_distance > 100]) / len(dim_distance)

0.69

### What fraction of the values of `dim_distance` are greater than 1000?

In [46]:
len(dim_distance[dim_distance > 1000]) / len(dim_distance)

0.0

### Due Wed Jan 10 - 1 pm

- Export notebook as .html: `File -> Save and Export Notebook as -> HTML`
- Upload `.html` file to Canvas