# Dictionaries and Tables

## Dictionaries

* Dictionaries are (sort of) a generalized version of arrays. Instead of `Index,Value` pairs of arrays, dictionares ues `Key:Value` pairs.
* They can be created via a comma-separated list of `Key:Value` pairs within curly braces `{}`
* Dictionaries are at the heart of a lot of what goes on in Python "under-the-hood"

![Python Dict](https://uwashington-astro300.github.io/A300_images/PyDict.jpg)

In [2]:
import numpy as np

In [3]:
my_dictionary = {'one': 1, 
                 'two': np.array([2, 2]), 
                 'three': np.array([3, 3, 3])}

my_dictionary

{'one': 1, 'two': array([2, 2]), 'three': array([3, 3, 3])}

In [4]:
type(my_dictionary)

dict

#### Access a `value` via the `key`

In [5]:
my_dictionary['two']

array([2, 2])

#### Add an `index` after the `key` for a slice of a `value`

In [6]:
my_dictionary['two'][0]

2

#### New items can be added to the dictionary using indexing

In [7]:
my_dictionary['ninety'] = np.array(['n', 'i', 'n', 'e', 't', 'y'])

my_dictionary

{'one': 1,
 'two': array([2, 2]),
 'three': array([3, 3, 3]),
 'ninety': array(['n', 'i', 'n', 'e', 't', 'y'], dtype='<U1')}

----

#### About Keys

- A given key can appear in a dictionary only once. Duplicate keys are not allowed.
- If you use a key a second time during the initial creation of a dictionary, the second occurrence will override the first.
- Keys are usually `str` datatypes, but `int` and `float` can be used as well.



In [8]:
my_dictionary.keys()

dict_keys(['one', 'two', 'three', 'ninety'])

#### Values can be pretty much anything at all - even other dictionaries.

In [9]:
my_dictionary.values()

dict_values([1, array([2, 2]), array([3, 3, 3]), array(['n', 'i', 'n', 'e', 't', 'y'], dtype='<U1')])

#### Dictionaries are Iterable

In [10]:
for my_key in my_dictionary:
    print (my_key)

one
two
three
ninety


In [11]:
for my_key, my_value in my_dictionary.items():
    print (my_key, my_value)

one 1
two [2 2]
three [3 3 3]
ninety ['n' 'i' 'n' 'e' 't' 'y']


---

# Astropy tables - `QTable`

### Provides a way for reading, storing and manipulating tables of all sorts of data in a very numpy-like way.

In [12]:
from astropy.table import QTable

### Make some arrays of data

In [13]:
my_star_id = np.array(['A5853', 'B4472', 'C3864', 'D7628', 'E2947', 'F5140', 'G5141'])

my_star_id

array(['A5853', 'B4472', 'C3864', 'D7628', 'E2947', 'F5140', 'G5141'],
      dtype='<U5')

In [14]:
my_star_parallax = np.array([768.07, 546.98, 415.18, 392.75, 374.49, 373.84, 367.71])

my_star_parallax

array([768.07, 546.98, 415.18, 392.75, 374.49, 373.84, 367.71])

In [15]:
my_star_gmag = np.array([8.98, 8.19, 11.03, 6.55, 8.52, 10.81, 10.50])

my_star_gmag

array([ 8.98,  8.19, 11.03,  6.55,  8.52, 10.81, 10.5 ])

### Use the arrays as the "data" part of a dictionary

In [16]:
my_star_name_dict = {'Star ID': my_star_id,
                     'Parallax': my_star_parallax,
                     'G Mag': my_star_gmag
                     }

In [17]:
for my_key, my_value in my_star_name_dict.items():
    print (my_key, my_value)

Star ID ['A5853' 'B4472' 'C3864' 'D7628' 'E2947' 'F5140' 'G5141']
Parallax [768.07 546.98 415.18 392.75 374.49 373.84 367.71]
G Mag [ 8.98  8.19 11.03  6.55  8.52 10.81 10.5 ]


## Arrays -> Dictionaries -> `QTable`

* Each Array is made into a Dictionary
* Each Dictionary become a Column in the `QTable`

In [18]:
star_table = QTable(my_star_name_dict)

In [19]:
star_table

<QTable length=7>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  A5853   768.07    8.98
  B4472   546.98    8.19
  C3864   415.18   11.03
  D7628   392.75    6.55
  E2947   374.49    8.52
  F5140   373.84   10.81
  G5141   367.71    10.5

In [20]:
print(star_table)

Star ID Parallax G Mag
------- -------- -----
  A5853   768.07  8.98
  B4472   546.98  8.19
  C3864   415.18 11.03
  D7628   392.75  6.55
  E2947   374.49  8.52
  F5140   373.84 10.81
  G5141   367.71  10.5


In [21]:
star_table.show_in_notebook()

In [22]:
star_table.info()

<QTable length=7>
  name    dtype 
-------- -------
 Star ID    str5
Parallax float64
   G Mag float64


In [23]:
star_table.info('stats')

<QTable length=7>
  name     mean    std    min    max  
-------- ------- ------- ------ ------
 Star ID      --      --     --     --
Parallax 462.717 137.428 367.71 768.07
   G Mag 9.22571 1.52033   6.55  11.03


### Number of values (rows)

* Again, many ways to count

In [24]:
np.size(star_table)

7

In [25]:
len(star_table)

7

## Slice Rows

In [26]:
star_table

<QTable length=7>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  A5853   768.07    8.98
  B4472   546.98    8.19
  C3864   415.18   11.03
  D7628   392.75    6.55
  E2947   374.49    8.52
  F5140   373.84   10.81
  G5141   367.71    10.5

In [27]:
star_table[0:2]

<QTable length=2>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  A5853   768.07    8.98
  B4472   546.98    8.19

In [28]:
star_table[[1,3,4]]

<QTable length=3>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  B4472   546.98    8.19
  D7628   392.75    6.55
  E2947   374.49    8.52

## Slice Columns

In [29]:
star_table['Star ID']

<Column name='Star ID' dtype='str5' length=7>
A5853
B4472
C3864
D7628
E2947
F5140
G5141

In [30]:
star_table['G Mag', 'Star ID']

<QTable length=7>
 G Mag  Star ID
float64   str5 
------- -------
   8.98   A5853
   8.19   B4472
  11.03   C3864
   6.55   D7628
   8.52   E2947
  10.81   F5140
   10.5   G5141

## Slice Rows and Colums

In [31]:
star_table['G Mag', 'Star ID'][0:2]

<QTable length=2>
 G Mag  Star ID
float64   str5 
------- -------
   8.98   A5853
   8.19   B4472

## Sorting

In [32]:
star_table.sort('G Mag')

In [33]:
star_table

<QTable length=7>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  D7628   392.75    6.55
  B4472   546.98    8.19
  E2947   374.49    8.52
  A5853   768.07    8.98
  G5141   367.71    10.5
  F5140   373.84   10.81
  C3864   415.18   11.03

In [34]:
star_table.sort('G Mag', reverse=True)

star_table

<QTable length=7>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  C3864   415.18   11.03
  F5140   373.84   10.81
  G5141   367.71    10.5
  A5853   768.07    8.98
  E2947   374.49    8.52
  B4472   546.98    8.19
  D7628   392.75    6.55

In [35]:
star_table[::-1]

<QTable length=7>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  D7628   392.75    6.55
  B4472   546.98    8.19
  E2947   374.49    8.52
  A5853   768.07    8.98
  G5141   367.71    10.5
  F5140   373.84   10.81
  C3864   415.18   11.03

In [36]:
star_table.show_in_notebook()

## Masking data

In [37]:
star_table[star_table['G Mag'] < 10.0]

<QTable length=4>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  A5853   768.07    8.98
  E2947   374.49    8.52
  B4472   546.98    8.19
  D7628   392.75    6.55

In [38]:
star_table[(star_table['G Mag'] < 10.0) & (star_table['G Mag'] > 8)]

<QTable length=3>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  A5853   768.07    8.98
  E2947   374.49    8.52
  B4472   546.98    8.19

In [39]:
star_table[(star_table['G Mag'] < 10.0) & 
           (star_table['G Mag'] > 8) &
           (star_table['Parallax'] > 400)]

<QTable length=2>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  A5853   768.07    8.98
  B4472   546.98    8.19

### The original `star_table` is unchanged. If you want a table of just the results, make a new table 

In [40]:
star_table

<QTable length=7>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  C3864   415.18   11.03
  F5140   373.84   10.81
  G5141   367.71    10.5
  A5853   768.07    8.98
  E2947   374.49    8.52
  B4472   546.98    8.19
  D7628   392.75    6.55

In [41]:
new_star_table = star_table[(star_table['G Mag'] < 10.0) & 
                            (star_table['G Mag'] > 8) &
                            (star_table['Parallax'] > 400)]

In [42]:
new_star_table

<QTable length=2>
Star ID Parallax  G Mag 
  str5  float64  float64
------- -------- -------
  A5853   768.07    8.98
  B4472   546.98    8.19

## QTable columns are `numpy` arrays

In [43]:
star_table['Parallax']

<Column name='Parallax' dtype='float64' length=7>
415.18
373.84
367.71
768.07
374.49
546.98
392.75

In [44]:
np.std(star_table['Parallax'])

137.4280642699285

In [45]:
np.median(star_table['Parallax'])

392.75

### You can send QTable columns to your functions

In [46]:
def find_two_parallax(my_parallax):
    result = 2 * my_parallax
    return result

In [47]:
find_two_parallax(
    my_parallax = star_table['Parallax']
)

<Column name='Parallax' dtype='float64' length=7>
 830.36
 747.68
 735.42
1536.14
 748.98
1093.96
  785.5

## Adding a column

In [48]:
my_two_parallax = find_two_parallax(
    my_parallax = star_table['Parallax']
)

In [49]:
my_two_parallax

<Column name='Parallax' dtype='float64' length=7>
 830.36
 747.68
 735.42
1536.14
 748.98
1093.96
  785.5

In [50]:
star_table['2Parallax'] = my_two_parallax

In [51]:
star_table

<QTable length=7>
Star ID Parallax  G Mag  2Parallax
  str5  float64  float64  float64 
------- -------- ------- ---------
  C3864   415.18   11.03    830.36
  F5140   373.84   10.81    747.68
  G5141   367.71    10.5    735.42
  A5853   768.07    8.98   1536.14
  E2947   374.49    8.52    748.98
  B4472   546.98    8.19   1093.96
  D7628   392.75    6.55     785.5

## Rearranging columns

In [52]:
my_new_order = ['2Parallax', 'Parallax', 'G Mag', 'Star ID']

In [53]:
another_star_table = star_table[my_new_order]

In [54]:
another_star_table

<QTable length=7>
2Parallax Parallax  G Mag  Star ID
 float64  float64  float64   str5 
--------- -------- ------- -------
   830.36   415.18   11.03   C3864
   747.68   373.84   10.81   F5140
   735.42   367.71    10.5   G5141
  1536.14   768.07    8.98   A5853
   748.98   374.49    8.52   E2947
  1093.96   546.98    8.19   B4472
    785.5   392.75    6.55   D7628